version: '3.8'

services:
  jetbrainsai2api:
    image: ghcr.io/caidaoli/jetbrainsai2api:latest
    ports:
      - "7860:7860"
    volumes:
      - ./data:/app/data
    env_file:
      - .env
    restart: unless-stopped
